# Generated by Django 5.1.4 on 2025-01-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_tag_post_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="tag",
            name="order",
            field=models.IntegerField(null=True),
        ),
    ]
